position:
  x: 1
  y: 2

micronaut:
  application:
    name: distributedGolCell
  server:
    port: 80

  jms:
    activemq:
      classic:
        enabled: true
        connection-string: tcp://localhost:61616

config.jms:
  tickQueue: tick-messages
  neighbourQueue: alive-messages
  
netty:
  default:
    allocator:
      max-order: 3
